plugins:
      # https://github.com/jest-community/eslint-plugin-jest
      - jest

env:
  node: true
  
extends:
         - 'airbnb-base'
         - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest
  
rules: 
   no-console: 0
   import/extensions: off
